plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def rawCastVersionName = {
    def value = System.getenv("RAW_CAST_VERSION")
            ?: System.getenv("GITHUB_REF_NAME")
            ?: "1.0"
    return value.startsWith("v") ? value.substring(1) : value
}()

android {
    namespace 'ink.mol.raw_cast'
    compileSdk 34

    defaultConfig {
        applicationId "ink.mol.raw_cast"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName rawCastVersionName
        resConfigs "en_US"
        resConfigs "hdpi"
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64', 'x86'
        }
        externalNativeBuild {
            cmake {
                cppFlags '-D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -O3 -ffast-math -fvisibility=hidden'
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        aidl = true
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22"
    implementation 'com.android.support:support-annotations:28.0.0'
}

apply from: "./artifacts.gradle"
